### ISSUE TITLE
java.lang.IllegalStateException: Library libpl_droidsonroids_gif.so for supported ABIs not found inAPK file

### ISSUE THREAD

**Issue by godfuture** [SimpleMobileTools/Simple-Gallery#1115]
I have installed the gallery app 6.0.4 in Yalp store. When I try to open any foto, it crashes. This did not happen in previous versions. I have installed LineageOS 14.1 with Android 7.1.2.

```
12-04 18:43:13.476 12794 12794 E AndroidRuntime: FATAL EXCEPTION: main
12-04 18:43:13.476 12794 12794 E AndroidRuntime: Process: com.simplemobiletools.gallery.pro, PID: 12794
12-04 18:43:13.476 12794 12794 E AndroidRuntime: android.view.InflateException:Binary XML file line #14: Binary XML file line #14: Error inflating class pl.droidsonroids.gif.GifTextureView
12-04 18:43:13.476 12794 12794 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class pl.droidsonroids.gif.GifTextureView
12-04 18:43:13.476 12794 12794 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.simplemobiletools.gallery.pro.fragments.PhotoFragment.onCreateView(SourceFile:83)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(SourceFile:2439)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.h.a(SourceFile:1460)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.h.f(SourceFile:1784)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.h.a(SourceFile:1852)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.a.f(SourceFile:802)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.h.b(SourceFile:2625)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.h.a(SourceFile:2411)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.h.b(SourceFile:2366)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.h.b(SourceFile:2243)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.a.e(SourceFile:654)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.fragment.app.l.finishUpdate(SourceFile:168)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.a.a.a.a.finishUpdate(SourceFile:61)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.o.a.b.populate(SourceFile:1244)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.o.a.b.populate(SourceFile:1092)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at androidx.o.a.b.setAdapter(SourceFile:540)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.a.a.a.b.setAdapter(SourceFile:78)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.simplemobiletools.gallery.pro.activities.ViewPagerActivity.updatePagerItems(SourceFile:367)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.simplemobiletools.gallery.pro.activities.ViewPagerActivity.gotMedia(SourceFile:1031)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.simplemobiletools.gallery.pro.activities.ViewPagerActivity.access$gotMedia(SourceFile:57)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.simplemobiletools.gallery.pro.activities.ViewPagerActivity$initViewPager$1.invoke(SourceFile:298)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.simplemobiletools.gallery.pro.activities.ViewPagerActivity$initViewPager$1.invoke(SourceFile:57)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.simplemobiletools.commons.extensions.ViewKt$onGlobalLayout$1.onGlobalLayout(SourceFile:29)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2106)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:621)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-04 18:43:13.476 12794 12794 E AndroidRuntime: Caused by: java.lang.ExceptionInInitializerError
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at pl.droidsonroids.gif.GifTextureView$b.<init>(SourceFile:162)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at pl.droidsonroids.gif.GifTextureView.a(SourceFile:101)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at pl.droidsonroids.gif.GifTextureView.<init>(SourceFile:70)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        ... 47 more
12-04 18:43:13.476 12794 12794 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Library libpl_droidsonroids_gif.so for supported ABIs not found inAPK file
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at pl.droidsonroids.gif.m.b(SourceFile:101)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at pl.droidsonroids.gif.m.a(SourceFile:58)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at pl.droidsonroids.gif.j.a(SourceFile:50)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        at pl.droidsonroids.gif.GifInfoHandle.<clinit>(SourceFile:25)
12-04 18:43:13.476 12794 12794 E AndroidRuntime:        ... 50 more
12-04 18:43:13.479  5592  5618 W ActivityManager:   Force finishing activity com.simplemobiletools.gallery.pro/.activities.ViewPagerActivity
12-04 18:43:13.484  5592  5618 W ActivityManager:   Force finishing activity com.simplemobiletools.gallery.pro/.activities.MediaActivity
12-04 18:43:13.986  5592  5631 W ActivityManager: Activity pause timeout for ActivityRecord{9640753 u0 com.simplemobiletools.gallery.pro/.activities.ViewPagerActivity t4271 f}
```

**Comment by tibbi** [comment]
yalp does not support app bundling, always more apps will become broken
