### ISSUE TITLE
ClassCastException when sharing edited screenshot from Editor

### ISSUE THREAD

**Issue by chilliger** [SimpleMobileTools/Simple-Gallery#1645]
Sharing a screenshot from the Editor does not work when Editor was selected directly from the screenshot notification [edit] button. It does work when the Editor is opened from within the gallery.
My device is running android 9.

> Attempt to cast generated internal exception:
java.lang.ClassCastException: android.net.Uri$HierarchicalUri cannot be cast to java.util.ArrayList
	at android.os.Bundle.getParcelableArrayList(Bundle.java:992)
	at com.whatsapp.ContactPickerFragment.A0q(:273713)
	at com.whatsapp.ContactPickerFragment.A0e(:273261)
	at X.1Xu.A0j(:186006)
	at X.1Xu.A0d(:185584)
	at X.1Xu.A0U(:185362)
	at X.1Xu.A0T(:185351)
	at X.2FN.onStart(:269479)
	at X.2Hr.onStart(:279437)
	at X.2LS.onStart(:289906)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7165)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2975)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by tibbi** [comment]
can you send a screenshot of the notification? I see only Share and Delete on my device

**Comment by chilliger** [comment]
<img src="https://user-images.githubusercontent.com/2310896/69007927-9de9e900-0944-11ea-90b6-222a164f6717.png" width="250">

**Comment by tibbi** [comment]
the editor has been fully rewritten in version 6.11.0 so this is no longer valid
