### ISSUE TITLE
Images fails to load when decrypted via OpenKeychain

### ISSUE THREAD

**Issue by lel-amri** [SimpleMobileTools/Simple-Gallery#1789]
Images decrypted by OpenKeychain ends up in `/user/0/org.sufficientlysecure.keychain/cache/temp/`. Simple-Gallery fails to load them with the following output in `logcat`:

    W Glide   : Load failed for /mnt/expand/8456f8d6-ef8e-4cfe-affc-c624a19f20f6/user/0/org.sufficientlysecure.keychain/cache/temp/eda09d4f-3e70-491a-b876-e9d677783bd9 with size [1080x1920]
    W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    W Glide   : There were 3 causes:
    W Glide   : java.io.FileNotFoundException(/mnt/expand/8456f8d6-ef8e-4cfe-affc-c624a19f20f6/user/0/org.sufficientlysecure.keychain/cache/temp/eda09d4f-3e70-491a-b876-e9d677783bd9 (Permission denied))
    W Glide   : java.io.FileNotFoundException(Permission denied)
    W Glide   : java.io.FileNotFoundException(Permission denied)
    W Glide   :  call GlideException#logRootCauses(String) for more detail
    W Glide   :   Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
    W Glide   : There was 1 cause:
    W Glide   : java.io.FileNotFoundException(/mnt/expand/8456f8d6-ef8e-4cfe-affc-c624a19f20f6/user/0/org.sufficientlysecure.keychain/cache/temp/eda09d4f-3e70-491a-b876-e9d677783bd9 (Permission denied))
    W Glide   :  call GlideException#logRootCauses(String) for more detail
    W Glide   :     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    W Glide   : There was 1 cause:
    W Glide   : java.io.FileNotFoundException(/mnt/expand/8456f8d6-ef8e-4cfe-affc-c624a19f20f6/user/0/org.sufficientlysecure.keychain/cache/temp/eda09d4f-3e70-491a-b876-e9d677783bd9 (Permission denied))
    W Glide   :  call GlideException#logRootCauses(String) for more detail
    W Glide   :       Cause (1 of 1): class java.io.FileNotFoundException: /mnt/expand/8456f8d6-ef8e-4cfe-affc-c624a19f20f6/user/0/org.sufficientlysecure.keychain/cache/temp/eda09d4f-3e70-491a-b876-e9d677783bd9 (Permission denied)
    W Glide   :   Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.os.ParcelFileDescriptor, LOCAL
    W Glide   : There was 1 cause:
    W Glide   : java.io.FileNotFoundException(Permission denied)
    W Glide   :  call GlideException#logRootCauses(String) for more detail
    W Glide   :     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    W Glide   : There was 1 cause:
    W Glide   : java.io.FileNotFoundException(Permission denied)
    W Glide   :  call GlideException#logRootCauses(String) for more detail
    W Glide   :       Cause (1 of 1): class java.io.FileNotFoundException: Permission denied
    W Glide   :   Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class android.content.res.AssetFileDescriptor, LOCAL
    W Glide   : There was 1 cause:
    W Glide   : java.io.FileNotFoundException(Permission denied)
    W Glide   :  call GlideException#logRootCauses(String) for more detail
    W Glide   :     Cause (1 of 1): class java.io.FileNotFoundException: Permission denied
    I Glide   : Root cause (1 of 3)
    I Glide   : java.io.FileNotFoundException: /mnt/expand/8456f8d6-ef8e-4cfe-affc-c624a19f20f6/user/0/org.sufficientlysecure.keychain/cache/temp/eda09d4f-3e70-491a-b876-e9d677783bd9 (Permission denied)
    I Glide   : 	at java.io.FileInputStream.open(Native Method)
    I Glide   : 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
    I Glide   : 	at java.io.FileInputStream.<init>(FileInputStream.java:99)
    I Glide   : 	at android.content.ContentResolver.openInputStream(ContentResolver.java:704)
    I Glide   : 	at com.bumptech.glide.load.n.n.b(SourceFile:2)
    I Glide   : 	at com.bumptech.glide.load.n.n.a(SourceFile:3)
    I Glide   : 	at com.bumptech.glide.load.n.n.a(SourceFile:2)
    I Glide   : 	at com.bumptech.glide.load.n.l.a(SourceFile:1)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.a(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:12)
    I Glide   : 	at com.bumptech.glide.load.engine.h.l(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.m(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.run(SourceFile:7)
    I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    I Glide   : 	at java.lang.Thread.run(Thread.java:761)
    I Glide   : 	at com.bumptech.glide.load.engine.b0.a$a$a.run(SourceFile:6)
    I Glide   : Root cause (2 of 3)
    I Glide   : java.io.FileNotFoundException: Permission denied
    I Glide   : 	at android.os.Parcel.openFileDescriptor(Native Method)
    I Glide   : 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:283)
    I Glide   : 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
    I Glide   : 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:981)
    I Glide   : 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:909)
    I Glide   : 	at com.bumptech.glide.load.n.i.a(SourceFile:3)
    I Glide   : 	at com.bumptech.glide.load.n.i.a(SourceFile:2)
    I Glide   : 	at com.bumptech.glide.load.n.l.a(SourceFile:1)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.a(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:12)
    I Glide   : 	at com.bumptech.glide.load.engine.h.l(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.a(SourceFile:52)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:20)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.d(SourceFile:6)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.a(SourceFile:11)
    I Glide   : 	at com.bumptech.glide.load.n.l.a(SourceFile:5)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.a(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:12)
    I Glide   : 	at com.bumptech.glide.load.engine.h.l(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.m(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.run(SourceFile:7)
    I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    I Glide   : 	at java.lang.Thread.run(Thread.java:761)
    I Glide   : 	at com.bumptech.glide.load.engine.b0.a$a$a.run(SourceFile:6)
    I Glide   : Root cause (3 of 3)
    I Glide   : java.io.FileNotFoundException: Permission denied
    I Glide   : 	at android.os.Parcel.openFileDescriptor(Native Method)
    I Glide   : 	at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:283)
    I Glide   : 	at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:200)
    I Glide   : 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:981)
    I Glide   : 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:909)
    I Glide   : 	at com.bumptech.glide.load.n.a.a(SourceFile:3)
    I Glide   : 	at com.bumptech.glide.load.n.a.a(SourceFile:2)
    I Glide   : 	at com.bumptech.glide.load.n.l.a(SourceFile:1)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:12)
    I Glide   : 	at com.bumptech.glide.load.engine.h.l(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.a(SourceFile:52)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:20)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.d(SourceFile:6)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.a(SourceFile:11)
    I Glide   : 	at com.bumptech.glide.load.n.l.a(SourceFile:5)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.a(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:12)
    I Glide   : 	at com.bumptech.glide.load.engine.h.l(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.a(SourceFile:52)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:20)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.d(SourceFile:6)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.a(SourceFile:11)
    I Glide   : 	at com.bumptech.glide.load.n.l.a(SourceFile:5)
    I Glide   : 	at com.bumptech.glide.load.o.q$a.a(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.y.a(SourceFile:12)
    I Glide   : 	at com.bumptech.glide.load.engine.h.l(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.m(SourceFile:4)
    I Glide   : 	at com.bumptech.glide.load.engine.h.run(SourceFile:7)
    I Glide   : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    I Glide   : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    I Glide   : 	at java.lang.Thread.run(Thread.java:761)
    I Glide   : 	at com.bumptech.glide.load.engine.b0.a$a$a.run(SourceFile:6)

I am clueless about Android dev. Byt looking at the issues in Glide's GitHub repository, I found that one of the possible sources of this error is too restrictive permissions.

**Comment by tibbi** [comment]
does any other downloaded gallery show the image well?

**Comment by lel-amri** [comment]
Yes. It works with "Photos" (`com.google.android.apps.photo`), which is the stock gallery app for my phone (Fairphone 2 with Google OS).

**Comment by tibbi** [comment]
I meant some app downloaded from somewhere, not a preinstalled one. Preinstalled apps work differently and have more permissions than other ones.

**Comment by lel-amri** [comment]
I just downloaded LeafPic Revived from F-Droid (`com.alienpants.leafpicrevived`). It successfully loaded the image from OpenKeychain.
