### ISSUE TITLE
Webp format support

### ISSUE THREAD

**Issue by Thewisem** [SimpleMobileTools/Simple-Gallery#2190]
Just had some pictures which were on webp format. Simple gallery crashed when viewing it
FATAL EXCEPTION: FrameDecoderExecutor-1
Process: com.simplemobiletools.gallery.pro, PID: 7060
java.lang.OutOfMemoryError: Failed to allocate a 57532720 byte allocation with 6471872 free bytes and 6MB until OOM
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:261)
	at b.b.b.a.b.b.y(SourceFile:2)
	at b.b.b.a.b.b.j(SourceFile:1)
	at b.b.b.a.b.b$e.run(SourceFile:5)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tibbi** [comment]
try restarting the device, we cannot really do much about it

**Comment by Thewisem** [comment]
Why not?

**Comment by Thewisem** [comment]
Is it a device issue?

**Comment by tibbi** [comment]
hard to say, could be

**Comment by Thewisem** [comment]
What does the error say?

**Comment by tibbi** [comment]
that your device is out of memory, guess it is leaking somewhere. In some app, could be the gallery too.

**Comment by Thewisem** [comment]
So the gallery leak needs to be fixed right?

**Comment by tibbi** [comment]
it is a too generic issue, might not be related to the gallery. Just restart your device.

**Comment by Thewisem** [comment]
One problem though. I could open up the webp file

**Comment by Thewisem** [comment]
I couldn't open this one though
