### ISSUE TITLE
Android 11 - Can't move file. Sometimes copy is not working. 

### ISSUE THREAD

**Issue by ProdanP** [SimpleMobileTools/Simple-Gallery#2215]
Hi!

Trying to move file do not work on Android 11 (Xiaomi Mi9). 
Throwing error - "Sometimes could not be moved." 
Probably because of the Scoped Storage.  

Also, Copy do not work for some folders. For example trying to copy a file from a random folder to 
"storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/Whatsapp Video" throws FileNotFoundException. Open failed: EPERM(Operation not permitted). 

Also, i've noticed that for app installed from Google Play these issues do not happen. 
Can you tell please why this can happen ? Maybe you have some special permissions/configurations for release builds ?

**Comment by tibbi** [comment]
not really, there is nothing special about the Google Play version. Arent those broken folders from "/Android/data"? That folder changed its handling from Android 11, we dont support it properly yet. If you are getting that error, it means that some files with the same name exist already. Anyway, what app version are you using?

**Comment by ProdanP** [comment]
Hi!. 
Seems like I managed the problem. 
I've updated:
 compileSdkVersion : 30 and targetSdkVersion 30. 
 
 So, we when trying to copy or move file to a folder other than Top Level directory it throws exception: 
 
 `2021-09-03 12:08:07.045 4324-4777/? W/MediaProvider: Forgot to handle a top level directory in getContentUriForFile?
2021-09-03 12:08:07.046 4324-4777/? E/MediaProvider: insertFileIfNecessary failed
    java.lang.IllegalArgumentException: Primary directory Android not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
        at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:2991)
        at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:2656)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:3352)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3915)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:3620)
        at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:7302)
        at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:7396)`
        
Also, when you try to create FileOutputStream/FileInputStream it throws: 
`java.io.FileNotFoundException: /storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Images/tmp_1629366715232.jpg: open failed: EPERM (Operation not permitted)`

Downgrading to compileSdkVersion : 29 and targetSdkVersion 29 solves the issue, but this is a temporary solution.

**Comment by tibbi** [comment]
so it works with 29? Thats the version we use. There is a reason we haven't updated to 30 yet.
