### ISSUE TITLE
Error at saving on overwrite image - UID does not have permission to content

### ISSUE THREAD

**Issue by finprog** [SimpleMobileTools/Simple-Gallery#2234]
Android 9 / LineageOS Version: '18.1'
If I edit an Image and save it with the original an error happens. If I save under a new file name everything is ok.

```` 
FATAL EXCEPTION: main
Process: com.simplemobiletools.gallery.pro, PID: 19771
  java.lang.SecurityException: UID 10268 does not have permission to content://media/external/images/media/38995 [user 0]  
at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at android.app.IActivityTaskManager$Stub$Proxy.finishActivity(IActivityTaskManager.java:4270)
at android.app.Activity.finish(Activity.java:6370)
at android.app.Activity.finish(Activity.java:6406)
at android.app.Activity.finishAfterTransition(Activity.java:6463)
at android.app.Activity.onBackPressed(Activity.java:3833)
at androidx.activity.ComponentActivity.access$001(SourceFile:1)
at androidx.activity.ComponentActivity$a.run(SourceFile:1)
at androidx.activity.OnBackPressedDispatcher.c(SourceFile:8)
at androidx.activity.ComponentActivity.onBackPressed(SourceFile:1)
at android.app.Activity.onKeyUp(Activity.java:3784)
at android.view.KeyEvent.dispatch(KeyEvent.java:2870)
at android.app.Activity.dispatchKeyEvent(Activity.java:4090)
at androidx.core.app.e.superDispatchKeyEvent(SourceFile:1)
at androidx.core.view.f.e(SourceFile:2)
at androidx.core.app.e.dispatchKeyEvent(SourceFile:3)
at androidx.appcompat.app.d.dispatchKeyEvent(SourceFile:4)
at h.i.dispatchKeyEvent(SourceFile:1)
at androidx.appcompat.app.g$k.dispatchKeyEvent(SourceFile:2)
at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:390)
at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5953)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5821)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5524)
at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5682)
at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3180)
at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3157)
at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:335)
at android.os.Looper.loop(Looper.java:183)
at android.app.ActivityThread.main(ActivityThread.java:7664)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
````

**Comment by tibbi** [comment]
1. what app version are you using?
2. is the file on an SD card or internal storage?
3. are you using the more advanced photoeditor SDK that is available on Google Play and Github?

**Comment by finprog** [comment]
Release 6.21.6 works better / other error.
The new picture is saved under the old name with the correct data, that's good.
It remains a copy of the image which is not deleted by the app, the know error pops up, then the app crashes.

**Comment by tibbi** [comment]
retry with 6.23.0 once it gets, whole file fetching will change on Android 11+
