### ISSUE TITLE
Simple Gallery crashes when showing image from Conversations

### ISSUE THREAD

**Issue by vanitasvitae** [SimpleMobileTools/Simple-Gallery#229]
Hi!
When I open an image from inside [conversations](https://github.com/siacs/conversations), the gallery crashes. Strangely however, this does no happen, if the app is opened in the background (eg. when I'm viewing images via the gallery at the same time).

```
04-13 16:03:00.442 29353 29353 V ExifParser: Reading exif...
04-13 16:03:00.443 29353 29353 D ExifParser: sections size: 9
04-13 16:03:00.547 29353 29353 D AndroidRuntime: Shutting down VM
04-13 16:03:00.552 29353 29353 E AndroidRuntime: FATAL EXCEPTION: main
04-13 16:03:00.552 29353 29353 E AndroidRuntime: Process: com.simplemobiletools.gallery, PID: 29353
04-13 16:03:00.552 29353 29353 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.simplemobiletools.gallery/com.simplemobiletools.gallery.activities.PhotoActivity}: java.lang.IllegalArgumentException: Width and height must be Target#SIZE_ORIGINAL or > 0
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2667)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2728)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6124)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:882)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.android.internal.os.ExecInit.main(ExecInit.java:68)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Width and height must be Target#SIZE_ORIGINAL or > 0
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.c.a.e.b(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.c.a.a.a(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.simplemobiletools.gallery.fragments.PhotoFragment.loadBitmap(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.simplemobiletools.gallery.fragments.PhotoFragment.loadBitmap$default(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.simplemobiletools.gallery.fragments.PhotoFragment.loadImage(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at com.simplemobiletools.gallery.fragments.PhotoFragment.onCreateView(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.p.performCreateView(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.v.a(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.v.e(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.v.a(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.h.e(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.v.b(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.v.a(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.v.b(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.v.d(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.s.o(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v4.b.q.onStart(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.support.v7.app.d.onStart(Unknown Source)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6699)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2630)
04-13 16:03:00.552 29353 29353 E AndroidRuntime: 	... 11 more
04-13 16:03:00.554 29353 29353 E AndroidRuntime: Error reporting crash
04-13 16:03:00.554 29353 29353 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
04-13 16:03:00.554 29353 29353 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-13 16:03:00.554 29353 29353 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:615)
04-13 16:03:00.554 29353 29353 E AndroidRuntime: 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5133)
04-13 16:03:00.554 29353 29353 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:97)
04-13 16:03:00.554 29353 29353 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
04-13 16:03:00.554 29353 29353 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
04-13 16:03:00.554 29353 29353 I Process : Sending signal. PID: 29353 SIG: 9
04-13 16:03:00.608  3866 18666 I ActivityManager: Process com.simplemobiletools.gallery (pid 29353) has died
```

**Comment by tibbi** [comment]
Hey, can you tell what app version are you using? Thanks

**Comment by vanitasvitae** [comment]
Hi! Right now I'm on v2.8.6, but I'm no longer experiencing this. Has there been an update?

**Comment by tibbi** [comment]
ye there has been some change a while ago that most likely fixed it, even if I was not fixing this specific issue

**Comment by vanitasvitae** [comment]
Nice! I'll close this now and mybe reopen, if the issue comes back :)
