### ISSUE TITLE
Simple Gallery crashes on app start under Android 13 => Crashlog

### ISSUE THREAD

**Issue by indiDing** [SimpleMobileTools/Simple-Gallery#2620]
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.220905.004.A2/2022092300:user/release-keys
package: com.simplemobiletools.gallery:217
process: com.simplemobiletools.gallery

android.content.res.Resources$NotFoundException: Resource ID #0x7f0800b3
at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:226)
at android.content.res.Resources.getValue(Resources.java:1437)
at androidx.appcompat.widget.j.k(SourceFile:4)
at androidx.appcompat.widget.j.q(SourceFile:3)
at androidx.appcompat.widget.j.p(SourceFile:1)
at a.a.k.a.a.d(SourceFile:1)
at androidx.appcompat.view.menu.j.getIcon(SourceFile:4)
at androidx.appcompat.view.menu.ActionMenuItemView.e(SourceFile:2)
at androidx.appcompat.widget.c.d(SourceFile:1)
at androidx.appcompat.view.menu.b.n(SourceFile:4)
at androidx.appcompat.widget.c.n(SourceFile:3)
at androidx.appcompat.widget.c.g(SourceFile:35)
at androidx.appcompat.view.menu.h.r(SourceFile:6)
at androidx.appcompat.view.menu.b.f(SourceFile:3)
at androidx.appcompat.widget.c.f(SourceFile:1)
at androidx.appcompat.view.menu.h.i(SourceFile:6)
at androidx.appcompat.view.menu.h.K(SourceFile:4)
at androidx.appcompat.view.menu.h.c0(SourceFile:4)
at androidx.appcompat.app.g.o0(SourceFile:37)
at androidx.appcompat.app.g.L(SourceFile:14)
at androidx.appcompat.app.g$b.run(SourceFile:2)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

**Comment by tibbi** [comment]
what app version is that? Does it happen after reinstalling too?

**Comment by indiDing** [comment]
It´s the latest Non-Pro, version (5.3.3), I think. Not supported any more?

**Comment by tibbi** [comment]
not sure, you shouldnt use the deprecated app version. We will update it soon and see what is wrong there.

**Comment by indiDing** [comment]
> not sure, you shouldnt use the deprecated app version. We will update it soon and see what is wrong there.

off course u are right. 
thx!
