### ISSUE TITLE
Gallery crash opening webp file

### ISSUE THREAD

**Issue by amebtw** [SimpleMobileTools/Simple-Gallery#2828]
I have a few images like [this one](https://mega.nz/file/AINEWIbI#jrxX4QoTTxvRCX7alYDYY51Ez2M9ovN8TOs0-4Z0nQY) that just crash the gallery to the main screen when I try to open them.
The gallery is fine displaying the thumbnail of them.
This is what [Scoop](https://github.com/TacoTheDank/Scoop) caught:
```typescript
FATAL EXCEPTION: FrameDecoderExecutor-0
Process: com.simplemobiletools.gallery.pro, PID: 30072
java.lang.OutOfMemoryError: Failed to allocate a 361344016 byte allocation with 25165824 free bytes and 183MB until OOM, target footprint 33738944, growth limit 201326592
 at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
 at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
 at java.nio.ByteBuffer.allocate(ByteBuffer.java:284)
 at m2.b.A(SourceFile:20)
 at m2.b.l(Unknown Source:0)
 at m2.b$e.run(SourceFile:52)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.os.HandlerThread.run(HandlerThread.java:67)

``` 
```typescript
FATAL EXCEPTION: FrameDecoderExecutor-2
Process: com.simplemobiletools.gallery.pro, PID: 30370
java.lang.OutOfMemoryError: Failed to allocate a 608000016 byte allocation with 50331648 free bytes and 93MB until OOM, target footprint 153160976, growth limit 201326592
 at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
 at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
 at java.nio.ByteBuffer.allocate(ByteBuffer.java:284)
 at m2.b.A(SourceFile:20)
 at m2.b.l(Unknown Source:0)
 at m2.b$e.run(SourceFile:52)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.os.HandlerThread.run(HandlerThread.java:67)

``` 
The default LineageOS 20 gallery is fine opening them.

**Comment by tibbi** [comment]
just restart your device

**Comment by amebtw** [comment]
Just did
```typescript
FATAL EXCEPTION: FrameDecoderExecutor-2
Process: com.simplemobiletools.gallery.pro, PID: 8781
java.lang.OutOfMemoryError: Failed to allocate a 608000016 byte allocation with 50331648 free bytes and 96MB until OOM, target footprint 150957112, growth limit 201326592
 at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
 at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
 at java.nio.ByteBuffer.allocate(ByteBuffer.java:284)
 at m2.b.A(SourceFile:20)
 at m2.b.l(Unknown Source:0)
 at m2.b$e.run(SourceFile:52)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by tibbi** [comment]
retry with 6.26.8 once it becomes available

**Comment by amebtw** [comment]
Same error sadly.

**Comment by OmlineEditor** [comment]
> Try a bigger [image](https://mega.nz/file/4QUn0bRb#s1ypT1oCqqfBTZ77UM5Sz4xBRCVEAaBr1clc4V71DN0).

if I use a large picture, then I can't open the full screen, the application crashes. but I can see the preview in the gallery.
there is a problem when opening large images - they are present.

**Comment by slavanap** [comment]
Here's a sample for testing. Image isn't displayed, app resets to start screen after an attempt to view the file.
https://file.io/JpP6dhVqD00a

**Comment by OmlineEditor** [comment]
> Here's a sample for testing. Image isn't displayed, app resets to start screen after an attempt to view the file. https://filebin.net/dqtn80stolbiuybt

I can open the image there is no problem
Galery v6.26.8 (F-Droid)

**Comment by slavanap** [comment]
I'm using 6.27.2 from F-Droid
