### ISSUE TITLE
Cannot start Simple-Gallery-1.25  - NullPointerException 

### ISSUE THREAD

**Issue by k3b** [SimpleMobileTools/Simple-Gallery#43]
When i try to start Simple-Gallery-1.25 on my android-4.2.2 tablet with 17000 photos on it i get a NullPointerException

	11-04 08:09:47.710 18136-18169/com.simplemobiletools.gallery E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
	   java.lang.RuntimeException: An error occured while executing doInBackground()
		   at android.os.AsyncTask$3.done(AsyncTask.java:299)
		   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
		   at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
		   at java.util.concurrent.FutureTask.run(FutureTask.java:239)
		   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
		   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
		   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
		   at java.lang.Thread.run(Thread.java:856)
		Caused by: java.lang.NullPointerException
		   at java.io.File.fixSlashes(File.java:185)
		   at java.io.File.<init>(File.java:134)
		   at com.simplemobiletools.gallery.a.a.a(Unknown Source)
		   at com.simplemobiletools.gallery.a.a.doInBackground(Unknown Source)
		   at android.os.AsyncTask$2.call(AsyncTask.java:287)
		   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
		   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
		   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
		   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
		   at java.lang.Thread.run(Thread.java:856)

**Comment by tibbi** [comment]
try 1.27 please when its available for download soon

**Comment by k3b** [comment]
I checked: Gallery-1.27 does not crash any more. thanks for fast fixing
